<a href="https://colab.research.google.com/github/MikolajWasowski/neural-network-course/blob/master/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [2]:
def max_relu(x):
    return max(x, 0.0)

In [3]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-2.7335335890013943,
 -1.330666513121881,
 -1.277191347953667,
 -1.0919200210831768,
 -0.9142126501081593,
 -0.9049750167259188,
 -0.7711805290042845,
 -0.7414117221498234,
 -0.7388840789975364,
 -0.6905051493940482,
 -0.6197260831881491,
 -0.5919615813457707,
 -0.5545998768909568,
 -0.5174421247244348,
 -0.4753751197638611,
 -0.4544684295720885,
 -0.3529259093739207,
 -0.3064032304822943,
 -0.1490558899187928,
 0.03348452119250463,
 0.037182909184842856,
 0.11141143084012232,
 0.16558726038566726,
 0.2957517613854091,
 0.31890541340086254,
 0.3381562955421335,
 0.39372257924902143,
 0.39601249465552707,
 0.5944166278402262,
 0.5956067325622599,
 0.6101477215323898,
 0.6245233616090707,
 0.6256101510664197,
 0.6713840455666099,
 0.6878108813355975,
 0.7412517104461745,
 0.748351472781827,
 0.8602302651154484,
 0.8922073986105642,
 0.8993045612411065,
 0.9086996822071947,
 0.9759303263745476,
 1.1473582045005566,
 1.1487614158645458,
 1.5263965575593479,
 1.5961360772886546,
 1.7386568

In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.033485, 0.037183, 0.111411, 0.165587, 0.295752,
       0.318905, 0.338156, 0.393723, 0.396012, 0.594417, 0.595607,
       0.610148, 0.624523, 0.62561 , 0.671384, 0.687811, 0.741252,
       0.748351, 0.86023 , 0.892207, 0.899305, 0.9087  , 0.97593 ,
       1.147358, 1.148761, 1.526397, 1.596136, 1.738657, 2.167218,
       2.587709, 2.62307 ])

In [6]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.733534            0.0
1 -1.330667            0.0
2 -1.277191            0.0
3 -1.091920            0.0
4 -0.914213            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [9]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [10]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-7.403061962574036,
 -5.130550970868773,
 -4.60369907620864,
 -4.499683582971531,
 -4.049431533809953,
 -2.821181462618788,
 -2.744023498772059,
 -2.6327699368148183,
 -2.4946794952654323,
 -2.4303047024440447,
 -2.2153148790412853,
 -1.6039886875790543,
 -1.5443257710301408,
 -1.522112898730917,
 -1.4419067791322717,
 -1.2043556710997425,
 -1.1511605392119815,
 -1.074998231218841,
 -1.0320643977254553,
 -0.9712495342742531,
 -0.8642020849524991,
 -0.7558046506919239,
 -0.6931592496662431,
 -0.5529304743486686,
 -0.47319198462623596,
 -0.3139088970445748,
 0.5256757426595592,
 0.5770280587934823,
 0.9252747607677908,
 1.1444922684939316,
 1.2258608403454199,
 1.436898708659635,
 1.4674380134503715,
 1.516045897839465,
 1.7135198278933705,
 1.9196503155211722,
 2.05318293654124,
 2.2515066160855444,
 2.326687246505225,
 2.4028685890690307,
 2.7583895501269584,
 2.947080736495237,
 3.1617222859837613,
 3.301872586195995,
 3.503544088377808,
 3.6308443227652405,
 3.6828895395266557,
 3.6

In [11]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.0006090128678728256,
 0.005878539939937595,
 0.00991542173251305,
 0.010990381422775253,
 0.017133603683728706,
 0.0561902443198682,
 0.06042506926422967,
 0.0670589497160419,
 0.07623200989782865,
 0.0808908104612198,
 0.09838361329698228,
 0.1674248787986899,
 0.17590731461476256,
 0.1791505950244607,
 0.19125024654589845,
 0.23070127325902784,
 0.24027716967048401,
 0.25445372142366324,
 0.2626840734002411,
 0.2746315135960845,
 0.2964621579817682,
 0.3195578141602275,
 0.3333306513151066,
 0.3651847841759416,
 0.3838610224478397,
 0.4221609093146383,
 0.6284739841392325,
 0.6403832763883623,
 0.7161156543544688,
 0.75850346988212,
 0.7730933035506724,
 0.8079739392425458,
 0.812667664336535,
 0.8199554807941958,
 0.8472922649416633,
 0.8720994342458253,
 0.8862688418698446,
 0.9047804135021685,
 0.9110632796058797,
 0.9170457863716686,
 0.9403854151030209,
 0.9501253344038406,
 0.9593681358545834,
 0.9644929956050043,
 0.9707884412376248,
 0.9741899994973415,
 0.9754668171381904

In [12]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -7.403062      0.000609
1 -5.130551      0.005879
2 -4.603699      0.009915
3 -4.499684      0.010990
4 -4.049432      0.017134

In [13]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [14]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [15]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-4.350686946121939,
 -4.057698584721998,
 -3.7334498580712077,
 -3.516637808044781,
 -3.2946934169763584,
 -3.2789374127816964,
 -3.169166733190464,
 -2.9639419335407733,
 -2.8034756070069844,
 -2.693922531409383,
 -2.6217174611800713,
 -2.613378179053804,
 -2.5772777148873693,
 -2.5445692689104598,
 -2.5000400246152497,
 -2.362827119293587,
 -2.183185349619496,
 -2.1816007674543716,
 -2.173653200794133,
 -2.1173946496918465,
 -2.096223830193229,
 -1.87956892315786,
 -1.8691282634807305,
 -1.8094431107819564,
 -1.7591913354712139,
 -1.6410165102289422,
 -1.5303868039466952,
 -1.5068329806632272,
 -1.4672737437242418,
 -1.3538072368645426,
 -1.3330583170297716,
 -1.298210300891148,
 -1.2370065070968534,
 -1.1904794101774023,
 -1.1145249987671293,
 -1.0777628235226893,
 -0.9816893719130171,
 -0.9770580725414221,
 -0.9596278357887548,
 -0.945826051484171,
 -0.8249827361886641,
 -0.7669462994309267,
 -0.7602992564312616,
 -0.7428415846217649,
 -0.7374784387609215,
 -0.5825965162632749,
 -

In [16]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9996673411457931,
 -0.9994023760485292,
 -0.9988572573472316,
 -0.9982374789579352,
 -0.9972540099410709,
 -0.9971662250093052,
 -0.9964717453757597,
 -0.9946859299932386,
 -0.9926823757186802,
 -0.9908979833303245,
 -0.9894913433920809,
 -0.9893155484876455,
 -0.9885201814627111,
 -0.987748853673757,
 -0.9866153624530432,
 -0.9824259677642817,
 -0.9749239187092443,
 -0.9748453235360132,
 -0.9744474412092975,
 -0.97144779478325,
 -0.9702312689245417,
 -0.9544537552479488,
 -0.953515027872856,
 -0.9477752316499799,
 -0.9424126210881426,
 -0.9276145360341744,
 -0.9104907632169544,
 -0.9063754097267266,
 -0.8990561145870855,
 -0.8749489284634658,
 -0.8699948187946431,
 -0.8612617202002297,
 -0.8445996734077253,
 -0.8307274930165307,
 -0.805656095199666,
 -0.7923679998968042,
 -0.7537962901243411,
 -0.7517895447151393,
 -0.7441108168044487,
 -0.737887575098525,
 -0.6777727677239966,
 -0.645150268358479,
 -0.6412531954920152,
 -0.6308589112822517,
 -0.627619276235235,
 -0.52455006994158

In [17]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.350687  -0.999667
1 -4.057699  -0.999402
2 -3.733450  -0.998857
3 -3.516638  -0.998237
4 -3.294693  -0.997254

In [18]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [19]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [20]:
data = np.random.randn(4, 5)
data

array([[ 0.653267,  1.165133, -0.775371, -1.524938,  0.914716],
       [-0.614224, -1.563109,  0.880877,  0.795192, -0.661427],
       [ 0.361902, -0.096228, -0.495139, -1.383095,  0.672059],
       [-0.783877, -1.098783, -1.117539, -1.206979,  0.926621]])

In [21]:
result = softmax(data)
result

array([[0.231476, 0.386196, 0.05547 , 0.026213, 0.300644],
       [0.09179 , 0.035539, 0.409364, 0.375749, 0.087558],
       [0.278151, 0.175921, 0.118052, 0.048578, 0.379298],
       [0.115836, 0.084544, 0.082973, 0.075874, 0.640773]])

In [22]:
result.sum(axis=1)

array([1., 1., 1., 1.])